teleport-per-world: true

# TODO: Add support for multiple homes per roles from vault (if possible)
max-home-amount: 2

# Set storage-type to JSON if you want to use JSON storage
# Set storage-type to MONGODB if you want to use MongoDB storage
# Set storage-type to MARIADB if you want to use MariaDB storage
storage-type: JSON