teleport-per-world: true

# TODO: Add support for multiple homes per roles from vault (if possible)
max-home-amount: 2

# Set storage-type to JSON if you want to use JSON storage
# Set storage-type to MONGODB if you want to use MongoDB storage
# Set storage-type to MYSQL if you want to use MYSQL storage
storage-type: JSON
MYSQL:
  host: localhost
  port: 3306
  database: example
  username: root
  password: root
  table-prefix: example
MONGODB:
  host: localhost
  port: 27017
  database: example
  username: root
  password: root
  collection: example