[versions]
paper = "1.21-R0.1-SNAPSHOT"
jupiter = "5.10.1"

[plugins]
shadow = "io.github.goooler.shadow:8.1.8"
spotless = "com.diffplug.spotless:6.17.0"
paperPlugin = "net.minecrell.plugin-yml.paper:0.6.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
inject = "team.unnamed:inject:2.0.0"
gui = "dev.triumphteam:triumph-gui:3.1.10"
command = "team.unnamed:commandflow-bukkit-commandmap:0.7.0"
lombok = "org.projectlombok:lombok:1.18.34"
hikari = "com.zaxxer:HikariCP:5.1.0"
mongo = "org.mongodb:mongodb-driver-sync:5.1.2"

jupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }