INSERT INTO SHRIMP_USERS (USER_ID, USER_NAME)
VALUES ('1', 'ALICE')
ON DUPLICATE KEY UPDATE USER_NAME = 'ALICE';

INSERT INTO SHRIMP_HOMES (HOME_ID, HOME_NAME, HOME_POSITION, CREATED_AT)
VALUES ('1', 'ALICE HOME', 'ALICE POSITION', NOW())
ON DUPLICATE KEY UPDATE HOME_NAME = 'ALICE HOME' AND HOME_POSITION = 'ALICE POSITION';

INSERT INTO SHRIMP_HOMES_USERS (HOME_ID, USER_ID)
VALUES ('1', '1');