SELECT SU.USER_ID, SU.USER_NAME, SH.HOME_ID, SH.HOME_NAME, SH.HOME_POSITION, SH.CREATED_AT
FROM SHRIMP_USERS AS SU
         INNER JOIN SHRIMP_HOMES SH ON SH.HOME_USER_ID = SU.USER_ID
WHERE SU.USER_ID = 1;

SELECT COUNT(SHU.HOME_ID) USER_HOMES
FROM SHRIMP_USERS AS SU
         INNER JOIN SHRIMP.SHRIMP_HOMES_USERS SHU ON SU.USER_ID = SHU.USER_ID
         INNER JOIN SHRIMP.SHRIMP_HOMES SH ON SHU.HOME_ID = SH.HOME_ID
WHERE SU.USER_ID = 1;

SELECT COUNT(SHU.USER_ID) HOME_USERS
FROM SHRIMP_USERS AS SU
         INNER JOIN SHRIMP.SHRIMP_HOMES_USERS SHU ON SU.USER_ID = SHU.USER_ID
         INNER JOIN SHRIMP.SHRIMP_HOMES SH ON SHU.HOME_ID = SH.HOME_ID
WHERE SH.HOME_ID = 1;