CREATE TABLE IF NOT EXISTS SHRIMP_USERS
(
  USER_ID   VARCHAR(36) PRIMARY KEY,
  USER_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SHRIMP_HOMES
(
  HOME_ID       VARCHAR(36) PRIMARY KEY,
  HOME_NAME     VARCHAR(255) NOT NULL,
  HOME_USER_ID  VARCHAR(36) NOT NULL,
  HOME_POSITION VARCHAR(255) NOT NULL,
  CREATED_AT    TIMESTAMP    NOT NULL,
  FOREIGN KEY (HOME_USER_ID) REFERENCES SHRIMP_USERS (USER_ID)
);


