CREATE TABLE IF NOT EXISTS SHRIMP_HOMES
(
  HOME_ID       VARCHAR(36) PRIMARY KEY,
  HOME_NAME     VARCHAR(255) NOT NULL,
  HOME_POSITION VARCHAR(255) NOT NULL,
  CREATED_AT    TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS SHRIMP_USERS
(
  USER_ID   VARCHAR(36) PRIMARY KEY,
  USER_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SHRIMP_HOMES_USERS
(
  HOME_ID VARCHAR(36) NOT NULL,
  USER_ID VARCHAR(36) NOT NULL,
  PRIMARY KEY (HOME_ID, USER_ID),
  FOREIGN KEY (HOME_ID) REFERENCES SHRIMP_HOMES (HOME_ID),
  FOREIGN KEY (USER_ID) REFERENCES SHRIMP_USERS (USER_ID)
);


